---
# configure kitchen driver in ~/.kitchen/config.yml or uncomment below:
#driver:
#  name: vagrant
#  customize:
#    memory: 1024

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8 # won't work out of the box: https://github.com/kubernetes/kubernetes/issues/23816
  - name: debian-9
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
